/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassifiersRouteImport } from './routes/classifiers'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as DocumentShaRouteImport } from './routes/document.$sha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiersRoute = ClassifiersRouteImport.update({
  id: '/classifiers',
  path: '/classifiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentShaRoute = DocumentShaRouteImport.update({
  id: '/document/$sha',
  path: '/document/$sha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classifiers': typeof ClassifiersRoute
  '/review': typeof ReviewRoute
  '/runs': typeof RunsRoute
  '/document/$sha': typeof DocumentShaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classifiers': typeof ClassifiersRoute
  '/review': typeof ReviewRoute
  '/runs': typeof RunsRoute
  '/document/$sha': typeof DocumentShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classifiers': typeof ClassifiersRoute
  '/review': typeof ReviewRoute
  '/runs': typeof RunsRoute
  '/document/$sha': typeof DocumentShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classifiers' | '/review' | '/runs' | '/document/$sha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classifiers' | '/review' | '/runs' | '/document/$sha'
  id: '__root__' | '/' | '/classifiers' | '/review' | '/runs' | '/document/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassifiersRoute: typeof ClassifiersRoute
  ReviewRoute: typeof ReviewRoute
  RunsRoute: typeof RunsRoute
  DocumentShaRoute: typeof DocumentShaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifiers': {
      id: '/classifiers'
      path: '/classifiers'
      fullPath: '/classifiers'
      preLoaderRoute: typeof ClassifiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$sha': {
      id: '/document/$sha'
      path: '/document/$sha'
      fullPath: '/document/$sha'
      preLoaderRoute: typeof DocumentShaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassifiersRoute: ClassifiersRoute,
  ReviewRoute: ReviewRoute,
  RunsRoute: RunsRoute,
  DocumentShaRoute: DocumentShaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
